(() => {
  'use strict';
  const $ = s => document.querySelector(s);
  const esc = s => String(s ?? '').replace(/[&<>"']/g, c => ({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
  const clean = s => String(s ?? '').replace(/\u00a0/g,' ').replace(/[ \t]+/g,' ').trim();
  const norm = s => clean(s).toLowerCase().normalize('NFKD').replace(/[\u0300-\u036f]/g,'').replace(/&/g,' and ').replace(/[^a-z0-9]+/g,' ').trim();
  const state = {files:[], audits:[], active:null, settings:null, refs:null};
  const defaults = {academicSession:'July - December 2026',academicYear:'2026-2027',institution:'UPES',strict:true};
  const stored = (k,d) => {try{return JSON.parse(localStorage.getItem(k)) ?? d}catch{return d}};
  state.settings = stored('cpa.settings',defaults);
  state.refs = stored('cpa.references',window.COURSE_GRID_DATA || {catalog:[],allocations:[]});

  const statusClass = s => s === 'N/A' ? 'NA' : s;
  const fileKey = f => `${f.name}:${f.size}:${f.lastModified}`;
  function addFiles(list){
    const known=new Set(state.files.map(fileKey));
    [...list].filter(f=>/\.(docx|pdf)$/i.test(f.name)).forEach(f=>{if(!known.has(fileKey(f))){state.files.push(f);known.add(fileKey(f))}});
    renderQueue();
  }
  function renderQueue(){
    $('#fileList').innerHTML=''; const t=$('#fileRowTemplate');
    state.files.forEach((f,i)=>{const n=t.content.cloneNode(true);n.querySelector('.file-main b').textContent=f.name;n.querySelector('.file-main span').textContent=`${(f.size/1024/1024).toFixed(2)} MB · ${f.webkitRelativePath||'Selected file'}`;n.querySelector('.file-icon').classList.add(/\.pdf$/i.test(f.name)?'pdf':'docx');n.querySelector('.remove').onclick=()=>{state.files.splice(i,1);renderQueue()};$('#fileList').append(n)});
    $('#queueText').textContent=state.files.length?`${state.files.length} supported file${state.files.length===1?'':'s'} ready`:'No course plans selected';
    $('#auditBtn').disabled=!state.files.length;$('#clearBtn').disabled=!state.files.length;
  }

  async function docxData(file){
    const buf=await file.arrayBuffer();
    const zip=await JSZip.loadAsync(buf.slice(0));
    const xmlFile=zip.file('word/document.xml'); const xml=xmlFile?await xmlFile.async('string'):'';
    const dom=new DOMParser().parseFromString(xml,'application/xml');
    const textOf=node=>[...node.getElementsByTagName('w:t')].map(x=>x.textContent).join(' ');
    const paragraphs=[...dom.getElementsByTagName('w:p')].map(textOf).map(clean).filter(Boolean);
    const holder=document.createElement('div');
    [...dom.getElementsByTagName('w:tbl')].forEach(tbl=>{const table=document.createElement('table');[...tbl.getElementsByTagName('w:tr')].forEach(tr=>{const row=table.insertRow();[...tr.children].filter(x=>x.localName==='tc').forEach(tc=>{row.insertCell().textContent=clean(textOf(tc))})});holder.append(table)});
    return {raw:paragraphs.join('\n'),html:holder,xml,pages:'',kind:'DOCX'};
  }
  async function pdfData(file){
    if(!window.pdfjsLib){await new Promise((resolve,reject)=>{const timer=setTimeout(()=>reject(new Error('PDF.js did not load')),12000);window.addEventListener('pdfjs-ready',()=>{clearTimeout(timer);resolve()},{once:true})})}
    window.pdfjsLib.GlobalWorkerOptions.workerSrc='./vendor/pdf.worker.min.mjs';
    const pdf=await window.pdfjsLib.getDocument({data:new Uint8Array(await file.arrayBuffer())}).promise; const pages=[];
    for(let n=1;n<=pdf.numPages;n++){const p=await pdf.getPage(n),tc=await p.getTextContent();pages.push(tc.items.map(x=>x.str).join(' '))}
    return {raw:pages.join('\n\n'),html:null,xml:'',pages:pdf.numPages,kind:'PDF'};
  }
  const lines = raw => raw.split(/\r?\n/).map(clean).filter(Boolean);
  function field(data, labels){
    const all=lines(data.raw); for(const label of labels){const nl=norm(label);for(let i=0;i<all.length;i++){const n=norm(all[i]);if(n.startsWith(nl)){let value=clean(all[i].replace(new RegExp('^'+label.replace(/[.*+?^${}()|[\]\\]/g,'\\$&'),'i'),'').replace(/^\s*[:|\-]?\s*/,''));if(value&&norm(value)!==nl)return value;if(all[i+1])return all[i+1]}}}
    if(data.html){for(const row of data.html.querySelectorAll('tr')){const cells=[...row.cells].map(c=>clean(c.textContent));for(let i=0;i<cells.length;i++)if(labels.some(x=>norm(x)===norm(cells[i])))return cells[i+1]||''}}
    return '';
  }
  function matchGrid(meta){
    const a=state.refs.allocations||[],c=state.refs.catalog||[]; const nf=norm(meta.faculty),nc=norm(meta.course),code=norm(meta.code);
    return a.find(x=>code&&norm(x.code)===code&&(!nf||norm(x.faculty)===nf))||a.find(x=>nf&&norm(x.faculty)===nf&&nc&&(norm(x.course)===nc||norm(x.course).includes(nc)||nc.includes(norm(x.course))))||c.find(x=>code&&norm(x.code)===code)||c.find(x=>nc&&norm(x.course)===nc)||null;
  }
  function ltp(data){
    if(data.html){for(const table of data.html.querySelectorAll('table')){const rows=[...table.rows].map(r=>[...r.cells].map(c=>clean(c.textContent)));for(let i=0;i<rows.length-1;i++){const labels=rows[i].map(norm);if(labels.includes('lecture')&&labels.includes('tutorial')&&labels.includes('practical')){const values=rows[i+1],numberAt=label=>{const v=values[labels.indexOf(label)]||'';return /^\d+(?:\.\d+)?$/.test(v)?+v:null};return [numberAt('lecture'),numberAt('tutorial'),numberAt('practical')]}}}}
    const m=data.raw.match(/Lecture\s+Tutorial\s+Practical[\s\S]{0,100}?\b(\d+(?:\.\d+)?)\s+(\d+(?:\.\d+)?)\s+(\d+(?:\.\d+)?)/i);return m?[+m[1],+m[2],+m[3]]:[null,null,null]
  }
  const numberValue=value=>{const m=clean(value).match(/\d+(?:\.\d+)?/);return m?+m[0]:null};
  function unitValue(value){const m=norm(value).match(/^unit\s*([ivx]+|\d+)$/);if(!m)return null;if(/^\d+$/.test(m[1]))return +m[1];return ({i:1,ii:2,iii:3,iv:4,v:5,vi:6,vii:7,viii:8,ix:9,x:10})[m[1]]||null}
  function unitCounts(data){
    const syllabus=new Set(),delivery=new Set();
    if(data.html){for(const table of data.html.querySelectorAll('table')){const rows=[...table.rows].map(r=>[...r.cells].map(c=>clean(c.textContent)));if(norm(rows.flat().join(' ')).includes('unit number')&&norm(rows.flat().join(' ')).includes('content'))rows.forEach(r=>{const n=unitValue(r[0]||'');if(n)syllabus.add(n)})}}
    if(!syllabus.size){const m=data.raw.match(/(?:course\s+syllabus\s+template|syllabus\s+template)([\s\S]*?)(?=course\s+plan\s+delivery)/i);if(m)[...m[1].matchAll(/\bunit\s*[-:]?\s*([ivx]+|\d+)\b/gi)].forEach(x=>{const n=unitValue('Unit '+x[1]);if(n)syllabus.add(n)})}
    [...data.raw.matchAll(/course\s+plan\s+delivery\s+unit\s*[-:]?\s*([ivx]+|\d+)/gi)].forEach(x=>{const n=unitValue('Unit '+x[1]);if(n)delivery.add(n)});
    return [[...syllabus].sort((a,b)=>a-b),[...delivery].sort((a,b)=>a-b)];
  }
  function deliveryCompletion(data){
    const totals={rows:0,sessionFull:0,actualFull:0,actualPartial:0};if(!data.html)return totals;
    for(const table of data.html.querySelectorAll('table')){const rows=[...table.rows].map(r=>[...r.cells].map(c=>clean(c.textContent))),headerIndex=rows.findIndex(r=>{const h=r.map(norm);return h.includes('topics to be covered')&&h.includes('date')&&h.includes('topics covered')});if(headerIndex<0)continue;const header=rows[headerIndex].map(norm),lectures=header.map((x,i)=>x==='lecture'?i:-1).filter(i=>i>=0),co=header.findIndex(x=>x==='co covered'||x==='course outcome covered');if(lectures.length<2||co<0)continue;const indexes=[lectures[0],header.indexOf('topics to be covered'),lectures[1],header.indexOf('date'),header.indexOf('topics covered'),co];rows.slice(headerIndex+1).forEach(row=>{const value=i=>clean(row[i]||''),planned=[value(indexes[0]),value(indexes[1])],actual=[value(indexes[2]),value(indexes[3]),value(indexes[4]),value(indexes[5])];if(![...planned,...actual].some(Boolean))return;totals.rows++;if(planned.every(Boolean))totals.sessionFull++;if(actual.every(Boolean))totals.actualFull++;else if(actual.some(Boolean))totals.actualPartial++})}
    return totals;
  }
  function targetAndReferences(data){
    const levels=new Set(),names={'text books':'Text Books','textbooks':'Text Books','web resources':'Web Resources','journals':'Journals','reference books':'Reference Books','moocs online courses':'MOOCs / Online Courses','moocs online course':'MOOCs / Online Courses','ai tools':'AI Tools'},refs=Object.fromEntries([...new Set(Object.values(names))].map(x=>[x,[]]));if(!data.html)return {levels:[],refs};
    for(const table of data.html.querySelectorAll('table')){const rows=[...table.rows].map(r=>[...r.cells].map(c=>clean(c.textContent))),tableText=norm(rows.flat().join(' '));if(tableText.includes('target')&&tableText.includes('level 1'))rows.forEach(row=>{const label=norm(row[0]||''),response=clean(row.slice(1).join(' '));if(['level 1','level 2','level 3'].includes(label)&&response&&!['no','n a','na','not selected'].includes(norm(response)))levels.add(label.replace(' ','-').replace(/^./,x=>x.toUpperCase()))});rows.forEach(row=>{const label=names[norm(row[0]||'')],value=clean(row.slice(1).join(' '));if(label&&value&&!['n a','na','nil','none'].includes(norm(value)))refs[label].push(value)})}
    return {levels:[...levels].sort(),refs};
  }
  function filenameComponents(filename,faculty,course,code){const base=norm(filename.replace(/\.(docx|pdf)$/i,'')),baseWords=base.split(' '),person=norm(faculty).replace(/^(dr|prof|professor)\s+/,'').split(' ').filter(x=>x.length>1),subject=norm(course).split(' ').filter(x=>x.length>2),compact=s=>norm(s).replaceAll(' ','');return {faculty:person.length>0&&compact(person.join(' '))&&compact(base).includes(compact(person.join(' '))),course:subject.length>0&&(subject.every(x=>baseWords.includes(x))||compact(base).includes(compact(subject.join(' ')))),code:!!compact(code)&&compact(filename).includes(compact(code))}}
  function uniqueLabels(raw,prefix,max){const found=[];for(let i=1;i<=max;i++)if(new RegExp(`\\b${prefix}\\s*${i}\\b`,'i').test(raw))found.push(i);return found}
  function dates(raw){return raw.match(/\b\d{1,2}[.\/-]\d{1,2}[.\/-]\d{2,4}\b/g)||[]}
  function predict(record){
    const m=window.COURSE_AUDIT_MODEL;if(!m)return {status:record.ruleStatus,confidence:0};
    const cols=['File Type','Faculty','Course Name','Course Code','Reference Course Code','Course Type','Semester','Student Year','Section','Criterion','Evidence / Remark'];
    const text=cols.map(c=>`${c.replaceAll(' ','_')}=${record[c]||''}`).join(' ').toLowerCase().normalize('NFKD').replace(/[\u0300-\u036f]/g,'');
    const tokens=text.match(/[\p{L}\p{N}_]{2,}/gu)||[], terms=tokens.concat(tokens.slice(0,-1).map((x,i)=>x+' '+tokens[i+1])); const counts={};terms.forEach(x=>counts[x]=(counts[x]||0)+1);
    const vec=[];let sq=0;for(const [term,count] of Object.entries(counts)){const idx=m.vocabulary[term];if(idx===undefined)continue;const value=(1+Math.log(count))*m.idf[idx];vec.push([idx,value]);sq+=value*value}const scale=Math.sqrt(sq)||1;
    const scores=m.classes.map((_,k)=>m.intercept[k]+vec.reduce((sum,[idx,v])=>sum+(v/scale)*m.coef[k][idx],0));const max=Math.max(...scores),exp=scores.map(x=>Math.exp(x-max)),total=exp.reduce((a,b)=>a+b,0),probs=exp.map(x=>x/total),best=probs.indexOf(Math.max(...probs));return {status:m.classes[best],confidence:probs[best]};
  }
  function auditFile(file,data){
    const raw=data.raw, low=norm(raw), meta={};
    meta.faculty=field(data,['Name of the Faculty','Name of the faculty member']);meta.designation=field(data,['Designation']);meta.cluster=field(data,['Cluster']);meta.program=field(data,['Program']);meta.course=field(data,['Course Name','Course']);meta.code=field(data,['Course Code']);meta.credits=field(data,['No. of credits','No of credits']);meta.semester=field(data,['Semester']);meta.session=field(data,['Session']);meta.academicYear=field(data,['Academic Year']);meta.ai=field(data,['AI-integrated Course']);meta.prerequisite=field(data,['Prerequisite','Prerequisite(s)']);
    const match=matchGrid(meta); if(match){meta.detectedCourse=match.course;meta.referenceCode=match.code;meta.courseType=String(match.type||'').replace('_',' + ');meta.year=match.year;meta.semester=meta.semester||match.semester}else{meta.detectedCourse=meta.course;meta.referenceCode='';meta.courseType='Undetermined';meta.year=Math.ceil((parseInt(meta.semester)||0)/2)||''}
    const [L,T,P]=ltp(data);if(meta.courseType==='Undetermined')meta.courseType=L>0&&P>0?'Theory + Lab':P>0?'Lab':L>0?'Theory':'Undetermined';
    const checks=[];const add=(section,criterion,status,evidence)=>checks.push({section,criterion,ruleStatus:status,evidence});
    [['Faculty name',meta.faculty],['Designation',meta.designation],['Cluster',meta.cluster],['Program',meta.program],['Course name',meta.course],['Course code',meta.code],['Number of credits',meta.credits],['Semester',meta.semester]].forEach(([n,v])=>add('Required Fields',n,v?'Pass':'Fail',v?`Entered: ${v}`:'Missing or not detected'));
    const sessionOk=meta.session&&(!state.settings.strict||norm(meta.session)===norm(state.settings.academicSession));add('Required Fields','Session',sessionOk?'Pass':meta.session?'Review':'Fail',meta.session?`Entered: ${meta.session}; configured: ${state.settings.academicSession}`:'Missing or not detected');
    const yearOk=meta.academicYear&&(!state.settings.strict||norm(meta.academicYear)===norm(state.settings.academicYear));add('Required Fields','Academic year',yearOk?'Pass':meta.academicYear?'Review':'Fail',meta.academicYear?`Entered: ${meta.academicYear}; configured: ${state.settings.academicYear}`:'Missing or not detected');
    add('Required Fields','AI-integrated selection',['yes','no'].includes(norm(meta.ai))?'Pass':'Fail',meta.ai?`Entered: ${meta.ai}`:'Yes/No selection missing');add('Required Fields','Prerequisite',meta.prerequisite?'Pass':'Fail',meta.prerequisite?`Entered: ${meta.prerequisite}`:'Missing');const ltpComplete=[L,T,P].every(x=>x!==null);add('Required Fields','L-T-P values',ltpComplete?'Pass':'Fail',`L=${L??'—'}, T=${T??'—'}, P=${P??'—'}`);const credits=numberValue(meta.credits),creditTotal=ltpComplete?L+T+P:null;add('Required Fields','Course credits equal L+T+P',ltpComplete&&credits===creditTotal?'Pass':ltpComplete?'Fail':'Review',`Course credits=${credits??'—'}; L+T+P=${creditTotal??'incomplete'}`);
    const fileParts=filenameComponents(file.name,meta.faculty,meta.detectedCourse||meta.course,meta.code);add('Required Fields','Filename contains faculty, subject and code',fileParts.faculty&&fileParts.course&&fileParts.code?'Pass':'Fail',`Faculty=${fileParts.faculty?'found':'missing'}; subject=${fileParts.course?'found':'missing'}; code=${fileParts.code?'found':'missing'}`);
    add('Grid Verification','Faculty/course assignment found',match?'Pass':'Review',match?`Matched: ${match.course}`:'No reliable match');add('Grid Verification','Course code agrees with reference',match&&norm(meta.code)===norm(match.code)?'Pass':'Review',`Document=${meta.code||'—'}; reference=${match?.code||'unavailable'}`);add('Grid Verification','Course type detected',meta.courseType==='Undetermined'?'Review':'Pass',meta.courseType);add('Grid Verification','Student year detected',meta.year?'Pass':'Review',`Semester ${meta.semester||'—'}; Year ${meta.year||'—'}`);
    const pos=uniqueLabels(raw,'PO',12),expected=+meta.year===1?11:12;add('Outcomes','Required Program Outcomes',pos.length>=expected?'Pass':'Fail',`${pos.length}/${expected} required PO labels detected`);['PSO1','PSO2','PSO3'].forEach(x=>add('Outcomes',`${x} included`,new RegExp(`\\b${x}\\b`,'i').test(raw)?'Pass':'Fail',new RegExp(`\\b${x}\\b`,'i').test(raw)?'Detected':'Not detected'));const cos=uniqueLabels(raw,'CO',9);add('Outcomes','Course Outcomes included',cos.length?'Pass':'Fail',cos.length?`CO1-CO${Math.max(...cos)} detected`:'No CO labels detected');const mapping=['program outcomes course outcomes','co po mapping','co po relationship matrix','co po pso mapping'].some(x=>low.includes(x));add('Outcomes','CO-PO-PSO mapping',mapping?'Pass':'Fail',mapping?'Mapping heading/table detected':'Mapping not detected');
    const aiYes=norm(meta.ai)==='yes',highlights=[...data.xml.matchAll(/<w:highlight\b[^>]*w:val="(?!none)([^"]+)"/g)].map(x=>x[1]),yellow=highlights.filter(x=>x==='yellow').length;add('AI and Formatting','AI integration rule',['yes','no'].includes(norm(meta.ai))?'Pass':'Fail',`AI-integrated Course=${meta.ai||'—'}`);add('AI and Formatting','AI Assignment option',aiYes?'Review':'N/A',aiYes?'Verify AI-assignment selection':'Not applicable');add('AI and Formatting','AI content highlighted yellow',data.kind==='PDF'?(aiYes?'Review':'N/A'):aiYes?(yellow?'Pass':'Fail'):'N/A',data.kind==='PDF'?'PDF colours require visual confirmation':aiYes?`${yellow} yellow marker(s)`:'Not applicable');add('AI and Formatting','No unnecessary highlighting',data.kind==='PDF'?'Review':(!aiYes&&highlights.length?'Review':'Pass'),data.kind==='PDF'?'PDF colours require visual confirmation':`${highlights.length} highlight marker(s)`);
    [['Assignment',['assignment']],['Test/Quiz',['test','quiz']],['Mid-Term Examination',['mid semester','mid term']],['End-Term Examination',['end semester','end term']]].forEach(([n,a])=>add('CO Assessment',`${n} field present`,a.some(x=>low.includes(x))?'Pass':'Fail',a.some(x=>low.includes(x))?'Detected':'Missing'));const dateValues=dates(raw);add('CO Assessment','Assessment planned dates',dateValues.length?'Pass':'Review',`${dateValues.length} full date value(s) detected`);
    let sessionNums=[];if(data.html){[...data.html.querySelectorAll('tr')].forEach(r=>{const first=clean(r.cells?.[0]?.textContent);if(/^\d{1,3}$/.test(first))sessionNums.push(+first)})}else{[...raw.matchAll(/(?:^|\n)\s*(\d{1,3})\s{2,}\S/g)].forEach(x=>sessionNums.push(+x[1]))}sessionNums=[...new Set(sessionNums.filter(x=>x>0&&x<=150))].sort((a,b)=>a-b);const expectedSessions=meta.courseType==='Lab'?(P||0)*15:(L||0)*15;add('Session Plan','Session rows versus credit rule',expectedSessions&&sessionNums.length===expectedSessions?'Pass':sessionNums.length?'Review':'Fail',`${sessionNums.length} unique rows detected; expected ${expectedSessions||'undetermined'}`);const continuous=sessionNums.length&&sessionNums.every((x,i)=>x===i+1);add('Session Plan','Continuous session numbering',continuous?'Pass':sessionNums.length?'Review':'Fail',sessionNums.length?`Session range 1-${Math.max(...sessionNums)}`:'No structured rows detected');add('Session Plan','Standard session format',low.includes('topics to be covered')&&(low.includes('co covered')||low.includes('course outcome'))?'Pass':'Review','Topic and CO fields validation');add('Session Plan','Planned/session dates entered',dateValues.length?'Pass':'Review',`${dateValues.length} full date(s) detected`);const [syllabusUnits,deliveryUnits]=unitCounts(data),sameUnits=syllabusUnits.length&&syllabusUnits.length===deliveryUnits.length&&syllabusUnits.every((x,i)=>x===deliveryUnits[i]);add('Session Plan','Syllabus units match Course Plan Delivery units',sameUnits?'Pass':!syllabusUnits.length||!deliveryUnits.length?'Review':'Fail',`Syllabus units=${syllabusUnits.length?syllabusUnits.join(', '):'not detected'}; delivery units=${deliveryUnits.length?deliveryUnits.join(', '):'not detected'}`);const completion=deliveryCompletion(data);add('Session Plan','Course Plan Delivery Session Plan rows filled',completion.rows&&completion.sessionFull===completion.rows?'Pass':completion.rows?'Fail':'Review',`${completion.sessionFull}/${completion.rows} rows have planned Lecture and Topics to be Covered`);add('Session Plan','Course Plan Delivery Actual Plan rows filled',completion.rows&&completion.actualFull===completion.rows?'Pass':completion.rows?'Fail':'Review',`${completion.actualFull}/${completion.rows} rows have Lecture, Date, Topics Covered and CO covered; ${completion.actualPartial} additional row(s) are partially filled`);
    add('Monitoring','Periodic monitoring section',low.includes('periodic monitoring')&&low.includes('planned')&&low.includes('taken')?'Pass':'Fail',low.includes('periodic monitoring')?'Section detected':'Missing or incomplete');add('Monitoring','Remedial classes section',low.includes('planning for remedial classes')||low.includes('remedial classes held')?'Pass':'Review',low.includes('remedial')?'Section detected':'Section not detected');const targetRefs=targetAndReferences(data);add('Target','Target Level selected',targetRefs.levels.length===1?'Pass':'Review',targetRefs.levels.length?targetRefs.levels.join(', '):'No Target Level selection detected');const refs=(low.includes('text books')||low.includes('textbooks'))&&(low.includes('web resources')||low.includes('reference books'));add('References and Sign-off','References section',refs?'Pass':'Fail',refs?'Headings detected':'References section not detected');['Text Books','Web Resources','Journals','Reference Books','MOOCs / Online Courses','AI Tools'].forEach(label=>{const entries=targetRefs.refs[label]||[];add('References and Sign-off',`Reference type provided: ${label}`,entries.length?'Pass':'Review',entries.length?`${entries.length} populated ${entries.length===1?'entry':'entries'} detected`:'No entry provided')});add('References and Sign-off','Indirect assessment section',low.includes('indirect assessment')?'Pass':'Fail',low.includes('indirect assessment')?'Section detected':'Section not detected');add('References and Sign-off','Faculty name and signature area',low.includes('signature of faculty')?'Review':'Fail',low.includes('signature of faculty')?'Visual signature confirmation required':'Area not detected');add('References and Sign-off','Cluster Head signature area',low.includes('signature of cluster head')||low.includes('signature of head')?'Review':'Fail',low.includes('signature of head')||low.includes('signature of cluster head')?'Visual confirmation required':'Area not detected');
    checks.forEach(r=>{Object.assign(r,{'File Type':data.kind,'Faculty':meta.faculty,'Course Name':meta.detectedCourse,'Course Code':meta.code,'Reference Course Code':meta.referenceCode,'Course Type':meta.courseType,'Semester':meta.semester,'Student Year':meta.year,'Section':r.section,'Criterion':r.criterion,'Evidence / Remark':r.evidence});const p=predict(r);r.modelStatus=p.status;r.confidence=p.confidence;r.finalStatus=r.ruleStatus;r.agreement=r.ruleStatus===p.status});
    const counts=countStatuses(checks),overall=counts.Fail?'Fail':counts.Review?'Review':'Pass';return {file:file.name,path:file.webkitRelativePath||file.name,size:file.size,meta,checks,counts,overall,error:null};
  }
  function countStatuses(rows){const c={Pass:0,Fail:0,Review:0,'N/A':0};rows.forEach(x=>c[x.finalStatus||x.ruleStatus]=(c[x.finalStatus||x.ruleStatus]||0)+1);return c}
  async function runBatch(){
    $('#auditBtn').disabled=true;$('#clearBtn').disabled=true;$('#progressWrap').classList.remove('hidden');state.audits=[];
    for(let i=0;i<state.files.length;i++){const file=state.files[i];setProgress(i,state.files.length,`Reading ${file.name}`);try{const data=/\.pdf$/i.test(file.name)?await pdfData(file):await docxData(file);state.audits.push(auditFile(file,data))}catch(e){state.audits.push({file:file.name,path:file.webkitRelativePath||file.name,size:file.size,meta:{},checks:[],counts:{Pass:0,Fail:1,Review:0,'N/A':0},overall:'Fail',error:e.message})}setProgress(i+1,state.files.length,`Audited ${i+1} of ${state.files.length}`);await new Promise(r=>setTimeout(r,0))}
    $('#auditBtn').disabled=false;$('#clearBtn').disabled=false;renderResults();
  }
  function setProgress(done,total,text){const pct=Math.round(done/Math.max(1,total)*100);$('#progressText').textContent=text;$('#progressPct').textContent=pct+'%';$('#progressBar').style.width=pct+'%'}
  function aggregate(){const checks=state.audits.flatMap(x=>x.checks),c=countStatuses(checks);return {checks,c}}
  function renderResults(){
    $('#results').classList.remove('hidden');const {checks,c}=aggregate();$('#kFiles').textContent=state.audits.length;$('#kChecks').textContent=checks.length;$('#kPass').textContent=c.Pass;$('#kFail').textContent=c.Fail;$('#kReview').textContent=c.Review;$('#kNA').textContent=c['N/A'];$('#reportMeta').textContent=`${state.settings.institution} · ${state.settings.academicSession} · ${state.settings.academicYear} · generated ${new Date().toLocaleString()}`;state.active=state.audits[0]?.file||null;renderSummaries();renderDetail();$('#results').scrollIntoView({behavior:'smooth'});
  }
  function renderSummaries(){const q=norm($('#fileSearch').value),filter=$('#statusFilter').value;const list=state.audits.filter(a=>(filter==='all'||a.overall===filter)&&(!q||norm([a.file,a.meta.faculty,a.meta.detectedCourse,a.meta.code].join(' ')).includes(q)));$('#summaryList').innerHTML=list.map(a=>`<article class="summary-card ${a.file===state.active?'active':''}" data-file="${esc(a.file)}"><div class="topline"><b>${esc(a.meta.detectedCourse||a.file)}</b><span class="badge ${statusClass(a.overall)}">${a.overall}</span></div><p>${esc(a.meta.faculty||'Faculty not detected')} · ${esc(a.meta.code||'Code not detected')}</p><div class="badges"><span class="badge Pass">${a.counts.Pass} pass</span><span class="badge Fail">${a.counts.Fail} fail</span><span class="badge Review">${a.counts.Review} review</span></div></article>`).join('')||'<div class="empty"><span>No matching files</span></div>';document.querySelectorAll('.summary-card').forEach(x=>x.onclick=()=>{state.active=x.dataset.file;renderSummaries();renderDetail()})}
  function renderDetail(){const a=state.audits.find(x=>x.file===state.active);if(!a){$('#detailPanel').innerHTML='<div class="empty"><b>Select a file</b></div>';return}if(a.error){$('#detailPanel').innerHTML=`<div class="detail-head"><h3>${esc(a.file)}</h3><span class="badge Fail">FAILED TO PROCESS</span></div><div class="issue"><b>Extraction error</b><span>${esc(a.error)}</span></div>`;return}const failed=a.checks.filter(x=>x.finalStatus==='Fail'),reviews=a.checks.filter(x=>x.finalStatus==='Review');$('#detailPanel').innerHTML=`<div class="detail-head"><div><h3>${esc(a.meta.detectedCourse||a.file)}</h3><p>${esc(a.file)}</p></div><span class="badge ${statusClass(a.overall)}">${a.overall}</span></div><div class="meta-grid">${[['Faculty',a.meta.faculty],['Course code',a.meta.code],['Reference code',a.meta.referenceCode],['Type',a.meta.courseType],['Semester',a.meta.semester],['Student year',a.meta.year],['Pass',a.counts.Pass],['Fail / Review',`${a.counts.Fail} / ${a.counts.Review}`]].map(([x,y])=>`<div class="meta-cell"><span>${x}</span><b>${esc(y||'—')}</b></div>`).join('')}</div><div class="detail-section"><h4>Why this file failed</h4>${failed.length?failed.map(issueHtml).join(''):'<p>No mandatory check failed.</p>'}<h4>Items requiring manual review</h4>${reviews.length?reviews.map(x=>issueHtml(x,true)).join(''):'<p>No review items recorded.</p>'}<h4>Complete validation register</h4><div class="table-wrap"><table class="checks"><thead><tr><th>Section</th><th>Check</th><th>Rule</th><th>Model</th><th>Confidence</th><th>Evidence</th></tr></thead><tbody>${a.checks.map(x=>`<tr><td>${esc(x.section)}</td><td>${esc(x.criterion)}</td><td><span class="badge ${statusClass(x.finalStatus)}">${x.finalStatus}</span></td><td class="${x.agreement?'':'model-disagree'}">${esc(x.modelStatus)}${x.agreement?'':' ⚠'}</td><td class="confidence">${(x.confidence*100).toFixed(1)}%</td><td>${esc(x.evidence)}</td></tr>`).join('')}</tbody></table></div></div>`}
  const issueHtml=(x,review=false)=>`<div class="issue ${review?'review':''}"><b>${esc(x.section)} — ${esc(x.criterion)}</b><span>${esc(x.evidence)}</span></div>`;
  function download(name,data,type){const a=document.createElement('a');a.href=URL.createObjectURL(new Blob([data],{type}));a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(a.href),1000)}
  function csvReport(){const head=['File Number','Source File','Faculty','Course Name','Course Code','Reference Course Code','Course Type','Semester','Student Year','Section','Criterion','Rule Status','Model Status','Model Confidence','Agreement','Final Status','Evidence / Remark'],rows=[head];state.audits.forEach((a,i)=>a.checks.forEach(x=>rows.push([i+1,a.file,a.meta.faculty,a.meta.detectedCourse,a.meta.code,a.meta.referenceCode,a.meta.courseType,a.meta.semester,a.meta.year,x.section,x.criterion,x.ruleStatus,x.modelStatus,x.confidence.toFixed(4),x.agreement?'Yes':'No—manual review recommended',x.finalStatus,x.evidence])));return '\ufeff'+rows.map(r=>r.map(v=>'"'+String(v??'').replaceAll('"','""')+'"').join(',')).join('\r\n')}
  function wordReport(){const {checks,c}=aggregate();const fileRows=state.audits.map((a,i)=>`<tr><td>${i+1}</td><td>${esc(a.meta.faculty||'—')}</td><td>${esc(a.meta.detectedCourse||a.file)}</td><td>${esc(a.meta.code||'—')}</td><td class="${a.overall}">${a.overall}</td><td>P=${a.counts.Pass}; F=${a.counts.Fail}; R=${a.counts.Review}; N/A=${a.counts['N/A']}</td></tr>`).join('');const dossiers=state.audits.map((a,i)=>`<div class="page"><h1>${i+1}. ${esc(a.meta.detectedCourse||a.file)}</h1><p><b>File:</b> ${esc(a.file)}<br><b>Faculty:</b> ${esc(a.meta.faculty||'—')} &nbsp; <b>Code:</b> ${esc(a.meta.code||'—')} &nbsp; <b>Reference:</b> ${esc(a.meta.referenceCode||'—')}</p><h2>Why this file failed</h2>${a.checks.filter(x=>x.finalStatus==='Fail').length?issuesTable(a.checks.filter(x=>x.finalStatus==='Fail')):'<p>No mandatory check failed.</p>'}<h2>Items requiring review</h2>${a.checks.filter(x=>x.finalStatus==='Review').length?issuesTable(a.checks.filter(x=>x.finalStatus==='Review')):'<p>No review items.</p>'}<h2>Complete validation register</h2><table><tr><th>Section</th><th>Criterion</th><th>Rule</th><th>Model</th><th>Confidence</th><th>Evidence</th></tr>${a.checks.map(x=>`<tr><td>${esc(x.section)}</td><td>${esc(x.criterion)}</td><td class="${statusClass(x.finalStatus)}">${x.finalStatus}</td><td>${x.modelStatus}</td><td>${(x.confidence*100).toFixed(1)}%</td><td>${esc(x.evidence)}</td></tr>`).join('')}</table></div>`).join('');return `<!doctype html><html><head><meta charset="utf-8"><style>@page{size:A4;margin:14mm}body{font:10pt Arial;color:#182133}h1{color:#17365d;font-size:18pt}h2{color:#2f75b5;font-size:13pt;margin-top:16pt}table{width:100%;border-collapse:collapse;margin:7pt 0}th,td{border:1px solid #cfd7e2;padding:5pt;vertical-align:top}th{background:#17365d;color:#fff}.Pass{background:#e2f0d9;color:#548235;font-weight:bold}.Fail{background:#fce4d6;color:#c00000;font-weight:bold}.Review{background:#fff2cc;color:#9c6500;font-weight:bold}.NA{background:#e7e6e6}.dashboard{display:flex;gap:8pt}.card{padding:10pt;background:#17365d;color:#fff}.page{page-break-before:always}</style></head><body><h1>Course Plan Batch Audit Report</h1><p>${esc(state.settings.institution)} · ${esc(state.settings.academicSession)} · ${esc(state.settings.academicYear)}</p><div class="dashboard"><div class="card">Files<br><b>${state.audits.length}</b></div><div class="card">Checks<br><b>${checks.length}</b></div><div class="card">Pass<br><b>${c.Pass}</b></div><div class="card">Fail<br><b>${c.Fail}</b></div><div class="card">Review<br><b>${c.Review}</b></div></div><h2>Consolidated file status</h2><table><tr><th>No.</th><th>Faculty</th><th>Course</th><th>Code</th><th>Status</th><th>Totals</th></tr>${fileRows}</table>${dossiers}</body></html>`}
  const issuesTable=rows=>`<table><tr><th>Section</th><th>Check</th><th>Explanation</th></tr>${rows.map(x=>`<tr><td>${esc(x.section)}</td><td>${esc(x.criterion)}</td><td>${esc(x.evidence)}</td></tr>`).join('')}</table>`;
  function openSettings(){const s=state.settings;$('#settingSession').value=s.academicSession;$('#settingYear').value=s.academicYear;$('#settingInstitution').value=s.institution;$('#settingStrict').checked=s.strict;$('#refStats').textContent=`${state.refs.catalog?.length||0} courses · ${state.refs.allocations?.length||0} faculty assignments`;$('#settingsDialog').showModal()}
  function saveSettings(){state.settings={academicSession:$('#settingSession').value.trim(),academicYear:$('#settingYear').value.trim(),institution:$('#settingInstitution').value.trim(),strict:$('#settingStrict').checked};localStorage.setItem('cpa.settings',JSON.stringify(state.settings))}
  $('#filePicker').onchange=e=>addFiles(e.target.files);$('#folderPicker').onchange=e=>addFiles(e.target.files);$('#clearBtn').onclick=()=>{state.files=[];renderQueue()};$('#auditBtn').onclick=runBatch;$('#fileSearch').oninput=renderSummaries;$('#statusFilter').onchange=renderSummaries;$('#csvBtn').onclick=()=>download('Course_Plan_Audit_Report.csv',csvReport(),'text/csv');$('#wordBtn').onclick=async()=>{const blob=await window.CourseAuditReport.build(state.audits,state.settings);const a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download='Course_Plan_Audit_Dashboard_Report.docx';a.click();setTimeout(()=>URL.revokeObjectURL(a.href),1500)};$('#printBtn').onclick=()=>window.print();$('#settingsBtn').onclick=openSettings;$('#saveSettings').onclick=saveSettings;
  $('#exportRefs').onclick=()=>download('course_faculty_reference_data.json',JSON.stringify(state.refs,null,2),'application/json');$('#importRefs').onchange=async e=>{try{const obj=JSON.parse(await e.target.files[0].text());if(!Array.isArray(obj.catalog)||!Array.isArray(obj.allocations))throw new Error('Expected catalog and allocations arrays');state.refs=obj;localStorage.setItem('cpa.references',JSON.stringify(obj));openSettings()}catch(err){alert('Could not import reference data: '+err.message)}};$('#resetRefs').onclick=()=>{if(confirm('Reset reference data to the embedded defaults?')){state.refs=window.COURSE_GRID_DATA;localStorage.removeItem('cpa.references');openSettings()}};
  const dz=$('#dropzone');['dragenter','dragover'].forEach(n=>dz.addEventListener(n,e=>{e.preventDefault();dz.classList.add('drag')}));['dragleave','drop'].forEach(n=>dz.addEventListener(n,e=>{e.preventDefault();dz.classList.remove('drag')}));dz.addEventListener('drop',e=>addFiles(e.dataTransfer.files));
  renderQueue();
})();
