(function(root,factory){
  if(typeof module==='object'&&module.exports)module.exports=factory(require('docx'));
  else root.CourseAuditReport=factory(root.docx);
})(typeof globalThis!=='undefined'?globalThis:this,function(D){
  'use strict';
  const {Document,Packer,Paragraph,TextRun,Table,TableRow,TableCell,Header,Footer,PageNumber,HeadingLevel,AlignmentType,WidthType,VerticalAlign,BorderStyle,PageBreak}=D;
  const C={navy:'17365D',blue:'2F75B5',green:'70AD47',red:'C00000',amber:'C99600',gray:'A5A5A5',white:'FFFFFF',black:'000000',paleBlue:'EAF2F8',paleRed:'FCE4D6',paleGreen:'E2F0D9',paleAmber:'FFF2CC',paleGray:'E7E6E6',line:'D9D9D9'};
  const statusFill={Pass:C.paleGreen,Fail:C.paleRed,'Partial Pass':C.paleAmber,Review:C.paleAmber,'N/A':C.paleGray};
  const statusText={Pass:'548235',Fail:C.red,'Partial Pass':'9C6500',Review:'9C6500','N/A':'666666'};
  const border={style:BorderStyle.SINGLE,size:4,color:C.line};
  const borders={top:border,bottom:border,left:border,right:border,insideHorizontal:border,insideVertical:border};
  const txt=(value,opt={})=>new TextRun({text:String(value??'—'),bold:!!opt.bold,color:opt.color||C.black,size:opt.size||18,italics:!!opt.italics,font:'Aptos'});
  const para=(value,opt={})=>new Paragraph({children:Array.isArray(value)?value:[txt(value,opt)],heading:opt.heading,alignment:opt.align||AlignmentType.LEFT,spacing:{before:opt.before||0,after:opt.after??100,line:opt.line||240},pageBreakBefore:!!opt.pageBreakBefore,keepNext:!!opt.keepNext});
  function cell(value,opt={}){return new TableCell({width:opt.width?{size:opt.width,type:WidthType.DXA}:undefined,verticalAlign:VerticalAlign.CENTER,shading:opt.fill?{fill:opt.fill}:undefined,margins:{top:100,bottom:100,left:110,right:110},borders,children:[new Paragraph({alignment:opt.align||AlignmentType.LEFT,spacing:{after:0,line:220},children:[txt(value,{bold:opt.bold,color:opt.color,size:opt.size||17})]})]})}
  function makeTable(headers,rows,widths,opt={}){
    const header=new TableRow({tableHeader:true,children:headers.map((x,i)=>cell(x,{width:widths[i],fill:opt.headerFill||C.navy,color:C.white,bold:true,size:opt.headerSize||17,align:opt.headerAlign||AlignmentType.LEFT}))});
    const body=rows.map((r,ri)=>new TableRow({cantSplit:true,children:r.map((v,i)=>{const status=opt.statusColumn===i?String(v):null;return cell(v,{width:widths[i],fill:status?statusFill[status]:(opt.stripe&&ri%2?C.paleBlue:undefined),color:status?statusText[status]:C.black,bold:!!status,size:opt.size||16,align:opt.centerColumns?.includes(i)?AlignmentType.CENTER:AlignmentType.LEFT})})}));
    return new Table({width:{size:100,type:WidthType.PERCENTAGE},columnWidths:widths,borders,rows:[header,...body]});
  }
  function kpis(items){const total=items.length,base=Math.floor(9360/total);return new Table({width:{size:100,type:WidthType.PERCENTAGE},columnWidths:items.map(()=>base),borders,rows:[new TableRow({children:items.map(([label,value,color])=>new TableCell({shading:{fill:color},verticalAlign:VerticalAlign.CENTER,margins:{top:170,bottom:170,left:80,right:80},borders,children:[new Paragraph({alignment:AlignmentType.CENTER,spacing:{after:30},children:[txt(value,{bold:true,color:C.white,size:34})]}),new Paragraph({alignment:AlignmentType.CENTER,spacing:{after:0},children:[txt(label,{bold:true,color:C.white,size:15})]})]}))})]})}
  const countAll=audits=>audits.flatMap(a=>a.checks||[]).reduce((o,x)=>(o[x.finalStatus]=(o[x.finalStatus]||0)+1,o),{Pass:0,Fail:0,Review:0,'N/A':0});
  function header(){return new Header({children:[para('COURSE PLAN AUDIT DASHBOARD  |  Consolidated Report',{bold:true,color:C.navy,size:18,align:AlignmentType.CENTER,after:70})]})}
  function footer(){return new Footer({children:[new Paragraph({alignment:AlignmentType.CENTER,children:[txt('Confidential audit record  |  Page ',{color:'6B6B6B',size:16}),new TextRun({children:[PageNumber.CURRENT],color:'6B6B6B',size:16})]})]})}
  function buildDocument(audits,settings){
    const totals=countAll(audits),allChecks=audits.flatMap(a=>a.checks||[]),fileCounts=audits.reduce((o,a)=>(o[a.overall]=(o[a.overall]||0)+1,o),{Pass:0,Fail:0,'Partial Pass':0,Review:0});
    const children=[];
    children.push(para('COURSE PLAN AUDIT DASHBOARD',{bold:true,color:C.navy,size:42,align:AlignmentType.CENTER,before:900,after:180}),para('Consolidated validation report for all submitted course plan files',{color:'666666',size:23,align:AlignmentType.CENTER,after:160}),para(`${settings.institution||'UPES'}  |  Academic Session ${settings.academicSession||'—'}  |  Academic Year ${settings.academicYear||'2026-2027'}`,{bold:true,color:C.blue,size:19,align:AlignmentType.CENTER,after:500}),kpis([['COURSE FILES',audits.length,C.navy],['DETAILED CHECKS',allChecks.length,C.blue],['PASSED',totals.Pass,C.green],['FAILED',totals.Fail,C.red],['REVIEW',totals.Review,C.amber]]),para('Audit basis: required fields, faculty and course reference matching, outcome mapping, AI formatting, assessment planning, session planning, monitoring, references and sign off verification.',{color:'666666',size:18,align:AlignmentType.CENTER,before:420,after:160}),para('Complete record of Pass, Fail, Review and N/A checks',{italics:true,color:'777777',size:17,align:AlignmentType.CENTER,after:0}),new Paragraph({children:[new PageBreak()]}));
    children.push(
      para('Report Contents',{heading:HeadingLevel.HEADING_1,bold:true,color:C.black,size:30,after:80}),
      para('This populated index is included in the generated file and does not require Word field updates.',{color:'666666',size:17,after:120}),
      makeTable(['Section','Report component'],[['1','Executive Audit Dashboard and consolidated file status'],['2','File Wise Detailed Audit Dossiers'],['3','Audit Interpretation Notes']],[900,8460],{headerFill:C.navy,stripe:true,size:16,centerColumns:[0]}),
      para('Course File Index',{heading:HeadingLevel.HEADING_2,bold:true,color:C.black,size:23,before:220,after:80}),
      makeTable(['No.','Faculty','Course','Code'],audits.map((a,i)=>[i+1,a.meta?.faculty||'—',a.meta?.detectedCourse||a.file,a.meta?.code||'—']),[600,2200,5060,1500],{headerFill:C.blue,stripe:true,size:14,centerColumns:[0,3]}),
      new Paragraph({children:[new PageBreak()]})
    );
    children.push(para('1 Executive Audit Dashboard',{heading:HeadingLevel.HEADING_1,bold:true,color:C.black,size:29,after:120}),kpis([['FILES PASSED',fileCounts.Pass,C.green],['PARTIAL PASS',fileCounts['Partial Pass'],C.amber],['FILES FAILED',fileCounts.Fail,C.red],['FILES FOR REVIEW',fileCounts.Review,C.amber],['PASS RATE',`${allChecks.length?(totals.Pass/allChecks.length*100).toFixed(1):'0.0'}%`,C.blue]]),para('Status Interpretation',{heading:HeadingLevel.HEADING_2,bold:true,color:C.black,size:23,before:260,after:80}),para([txt('Fail  ',{bold:true,color:C.red,size:18}),txt('More than 10 checks failed.   ',{size:18}),txt('Partial Pass  ',{bold:true,color:'9C6500',size:18}),txt('One to 10 checks failed.   ',{size:18}),txt('Review  ',{bold:true,color:'9C6500',size:18}),txt('No failures, but manual confirmation is required.   ',{size:18}),txt('Pass  ',{bold:true,color:'548235',size:18}),txt('No unresolved mandatory issue remains.',{size:18})],{after:180}));
    children.push(para('Consolidated File Status',{heading:HeadingLevel.HEADING_2,bold:true,color:C.black,size:23,after:100}));
    children.push(makeTable(['No.','Faculty','Course','Code','Overall','Check totals'],audits.map((a,i)=>[i+1,a.meta?.faculty||'—',a.meta?.detectedCourse||a.file,a.meta?.code||'—',a.overall,`Pass=${a.counts.Pass}; Fail=${a.counts.Fail}; Review=${a.counts.Review}; N/A=${a.counts['N/A']}`]),[520,1650,2500,1050,900,2740],{statusColumn:4,stripe:true,size:15,centerColumns:[0,3,4]}));
    children.push(new Paragraph({children:[new PageBreak()]}),para('2 File Wise Detailed Audit Dossiers',{heading:HeadingLevel.HEADING_1,bold:true,color:C.black,size:29,after:100}),para('Each dossier records the detected metadata, audit totals, explicit failure causes, manual review items and complete validation evidence.',{size:18,after:100}));
    audits.forEach((a,i)=>{
      children.push(para(`2.${i+1} File ${i+1} ${a.meta?.detectedCourse||a.file}`,{heading:HeadingLevel.HEADING_2,bold:true,color:C.black,size:25,pageBreakBefore:i>0,after:100}));
      children.push(new Table({width:{size:100,type:WidthType.PERCENTAGE},borders,rows:[new TableRow({children:[cell(`OVERALL STATUS  ${a.overall}  |  Pass=${a.counts.Pass}; Fail=${a.counts.Fail}; Review=${a.counts.Review}; N/A=${a.counts['N/A']}`,{fill:statusFill[a.overall],color:statusText[a.overall],bold:true,size:20,align:AlignmentType.CENTER})]})]}));
      children.push(para('',{after:40}),makeTable(['Field','Detected value','Field','Detected value'],[['Source file',a.file,'File type',/\.pdf$/i.test(a.file)?'PDF':'DOCX'],['Faculty',a.meta?.faculty||'—','Course type',a.meta?.courseType||'—'],['Course code',a.meta?.code||'—','Reference code',a.meta?.referenceCode||'—'],['Semester',a.meta?.semester||'—','Student year',a.meta?.year||'—'],['Academic session',a.meta?.session||'—','Academic year',a.meta?.academicYear||settings.academicYear||'2026-2027']],[1300,3360,1300,3400],{headerFill:C.blue,stripe:true,size:16}));
      const failed=(a.checks||[]).filter(x=>x.finalStatus==='Fail'),reviews=(a.checks||[]).filter(x=>x.finalStatus==='Review');
      children.push(para('Why This File Failed',{heading:HeadingLevel.HEADING_3,bold:true,color:C.black,size:21,before:220,after:80}));
      children.push(failed.length?makeTable(['Section','Failed criterion','Page','Reason and evidence'],failed.map(x=>[x.section,x.criterion,x.pageRef||x['Page Number']||'Not located',x.evidence]),[1600,2200,1250,4310],{headerFill:C.red,stripe:true,size:15,centerColumns:[2]}):para('No mandatory check failed.',{size:17}));
      children.push(para('Items Requiring Manual Review',{heading:HeadingLevel.HEADING_3,bold:true,color:C.black,size:21,before:220,after:80}));
      children.push(reviews.length?makeTable(['Section','Review criterion','Page','Reason and evidence'],reviews.map(x=>[x.section,x.criterion,x.pageRef||x['Page Number']||'Not located',x.evidence]),[1600,2200,1250,4310],{headerFill:C.amber,stripe:true,size:15,centerColumns:[2]}):para('No manual review items were recorded.',{size:17}));
      children.push(para('Complete Check and Validation Register',{heading:HeadingLevel.HEADING_3,bold:true,color:C.black,size:21,before:220,after:80}));
      children.push(makeTable(['Section','Criterion','Page','Status','Evidence and validation remark'],(a.checks||[]).map(x=>[x.section,x.criterion,x.pageRef||x['Page Number']||'Not located',x.finalStatus,x.evidence]),[1500,2200,1200,900,3560],{statusColumn:3,stripe:true,size:14,centerColumns:[2,3]}));
    });
    children.push(new Paragraph({children:[new PageBreak()]}),para('3 Audit Interpretation Notes',{heading:HeadingLevel.HEADING_1,bold:true,color:C.black,size:29,after:100}),makeTable(['Audit concept','Interpretation'],[['Automated extraction','Complex layouts, scans, merged cells, images and unusual headings may require manual confirmation.'],['Page references','PDF page numbers are exact. DOCX references are approximate only when Word pagination markers exist; otherwise upload a PDF for exact navigation.'],['Fail status','More than 10 failed checks produce an overall Fail status.'],['Partial Pass status','One to 10 failed checks produce an overall Partial Pass status.'],['Review status','The content may be present but requires visual or reference confirmation.'],['PDF signatures and highlights','Signature images and highlight colours require visual verification.'],['Reference code mismatch','Confirm the curriculum and academic handbook applicable to the student batch.'],['Session counts','Combined periods, laboratory blocks and merged rows may require manual interpretation.']],[2300,7060],{headerFill:C.navy,stripe:true,size:16}),para('A little help from Brijmohan',{italics:true,bold:true,color:'666666',size:18,align:AlignmentType.CENTER,before:500,after:0}));
    return new Document({creator:'Course Plan Audit Studio',title:'Course Plan Audit Dashboard',description:'Consolidated Course Plan audit report',styles:{default:{document:{run:{font:'Aptos',size:20,color:C.black},paragraph:{spacing:{after:100,line:240}}}},paragraphStyles:[{id:'Title',name:'Title',basedOn:'Normal',next:'Normal',run:{size:42,bold:true,color:C.black,font:'Aptos Display'},paragraph:{alignment:AlignmentType.CENTER,spacing:{after:180}}},{id:'Heading1',name:'Heading 1',basedOn:'Normal',next:'Normal',quickFormat:true,run:{size:29,bold:true,color:C.black,font:'Aptos Display'},paragraph:{spacing:{before:220,after:100},keepNext:true}},{id:'Heading2',name:'Heading 2',basedOn:'Normal',next:'Normal',quickFormat:true,run:{size:25,bold:true,color:C.black,font:'Aptos Display'},paragraph:{spacing:{before:180,after:80},keepNext:true}},{id:'Heading3',name:'Heading 3',basedOn:'Normal',next:'Normal',quickFormat:true,run:{size:21,bold:true,color:C.black,font:'Aptos Display'},paragraph:{spacing:{before:160,after:70},keepNext:true}}]},sections:[{properties:{page:{size:{width:12240,height:15840},margin:{top:720,right:720,bottom:720,left:720,header:360,footer:360}}},headers:{default:header()},footers:{default:footer()},children}]});
  }
  return {build:async(audits,settings)=>Packer.toBlob(buildDocument(audits,settings)),buildBuffer:async(audits,settings)=>Packer.toBuffer(buildDocument(audits,settings)),buildDocument};
});
